### ISSUE TITLE
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Unable to complete login process due to delay in opening server connection.

### ISSUE THREAD

**Issue by mloskot** [potatoqualitee/mssqlsuite#25]
Not saying this is a bug, but perhaps it's worth troubleshoot

![image](https://user-images.githubusercontent.com/80741/216157951-d877d336-4b2b-4a39-935b-0145eba06a77.png)

```yaml
  test-mssql:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: localdb
```

Connection in separate check step works fien

```yaml
      - name: Check
        run: |
          Get-OdbcDriver -Platform 64-bit | Select-Object -ExpandProperty Name
          sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
```

![image](https://user-images.githubusercontent.com/80741/216159425-33384603-ace7-4e83-8a5f-dd9a907406c8.png)

p.s Thanks for this action!

**Comment by Max84** [comment]
Hi,

I've the same error. Do you find how to fix it? (not sure it's a problem too).

Thanks,

**Comment by mloskot** [comment]
I forgot about this report. Well, it looks like the password is required on Windows.
Here is what works for me:
https://github.com/nanodbc/nanodbc/blob/62c27ec71842302a6fa28efc59637515441706c1/.github/workflows/ci-windows.yml#L123-L130

**Comment by mloskot** [comment]
@Max84 I completely forgot about this issue. Well, it looks like explicit credentials are required and no implicit Windows authentication is possible. Here is what I do and what works:
https://github.com/nanodbc/nanodbc/blob/012d9d196dcf6d81d9e2ff20c5022bb8c5136a59/.github/workflows/ci-windows.yml#L123-L134

```yaml
   - name: Install SQL Server
      uses: potatoqualitee/mssqlsuite@v1.7
      with:
        install: localdb
        sa-password: Password!123
        version: ${{ matrix.mssql }}
    - name: Check
      run: |
        sqlcmd -S "(localdb)\MSSQLLocalDB" -U sa -P "Password!123" -Q "SELECT @@VERSION;"
```
